<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-12 15:16:43.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */
namespace Tracestay\Bundle\TracestayBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Entity\Campus
 *
 * @ORM\Entity(repositoryClass="CampusRepository")
 * @ORM\Table(name="campus", indexes={@ORM\Index(name="fk_campus_university1_idx", columns={"university_id"})})
 */
class Campus
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $tTitle;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $tDescription;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $bIsMain;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    protected $tCampusCode;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $dEstablishmentYear;

    /**
     * @ORM\Column(type="string", length=225, nullable=true)
     */
    protected $tAddressTitle;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $tStreet1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $tStreet2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $tCity;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $tState;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $nCountry;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    protected $tZipCode;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $nLatitude;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $nLongitude;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $dCreatedAt;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $dUpdatedAt;

    /**
     * 
     * @ORM\Column(type="integer")
     */
    protected $university_id;

    /**
     * @ORM\OneToMany(targetEntity="CampusHasProperty", mappedBy="campus")
     * @ORM\JoinColumn(name="id", referencedColumnName="campusId")
     */
    protected $campusHasProperties;

    /**
     * @ORM\ManyToOne(targetEntity="University", inversedBy="campuses")
     * @ORM\JoinColumn(name="university_id", referencedColumnName="id")
     */
    protected $university;

    public function __construct()
    {
        $this->campusHasProperties = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\Campus
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of tTitle.
     *
     * @param string $tTitle
     * @return \Entity\Campus
     */
    public function setTTitle($tTitle)
    {
        $this->tTitle = $tTitle;

        return $this;
    }

    /**
     * Get the value of tTitle.
     *
     * @return string
     */
    public function getTTitle()
    {
        return $this->tTitle;
    }

    /**
     * Set the value of tDescription.
     *
     * @param string $tDescription
     * @return \Entity\Campus
     */
    public function setTDescription($tDescription)
    {
        $this->tDescription = $tDescription;

        return $this;
    }

    /**
     * Get the value of tDescription.
     *
     * @return string
     */
    public function getTDescription()
    {
        return $this->tDescription;
    }

    /**
     * Set the value of bIsMain.
     *
     * @param boolean $bIsMain
     * @return \Entity\Campus
     */
    public function setBIsMain($bIsMain)
    {
        $this->bIsMain = $bIsMain;

        return $this;
    }

    /**
     * Get the value of bIsMain.
     *
     * @return boolean
     */
    public function getBIsMain()
    {
        return $this->bIsMain;
    }

    /**
     * Set the value of tCampusCode.
     *
     * @param string $tCampusCode
     * @return \Entity\Campus
     */
    public function setTCampusCode($tCampusCode)
    {
        $this->tCampusCode = $tCampusCode;

        return $this;
    }

    /**
     * Get the value of tCampusCode.
     *
     * @return string
     */
    public function getTCampusCode()
    {
        return $this->tCampusCode;
    }

    /**
     * Set the value of dEstablishmentYear.
     *
     * @param \DateTime $dEstablishmentYear
     * @return \Entity\Campus
     */
    public function setDEstablishmentYear($dEstablishmentYear)
    {
        $this->dEstablishmentYear = $dEstablishmentYear;

        return $this;
    }

    /**
     * Get the value of dEstablishmentYear.
     *
     * @return \DateTime
     */
    public function getDEstablishmentYear()
    {
        return $this->dEstablishmentYear;
    }

    /**
     * Set the value of tAddressTitle.
     *
     * @param string $tAddressTitle
     * @return \Entity\Campus
     */
    public function setTAddressTitle($tAddressTitle)
    {
        $this->tAddressTitle = $tAddressTitle;

        return $this;
    }

    /**
     * Get the value of tAddressTitle.
     *
     * @return string
     */
    public function getTAddressTitle()
    {
        return $this->tAddressTitle;
    }

    /**
     * Set the value of tStreet1.
     *
     * @param string $tStreet1
     * @return \Entity\Campus
     */
    public function setTStreet1($tStreet1)
    {
        $this->tStreet1 = $tStreet1;

        return $this;
    }

    /**
     * Get the value of tStreet1.
     *
     * @return string
     */
    public function getTStreet1()
    {
        return $this->tStreet1;
    }

    /**
     * Set the value of tStreet2.
     *
     * @param string $tStreet2
     * @return \Entity\Campus
     */
    public function setTStreet2($tStreet2)
    {
        $this->tStreet2 = $tStreet2;

        return $this;
    }

    /**
     * Get the value of tStreet2.
     *
     * @return string
     */
    public function getTStreet2()
    {
        return $this->tStreet2;
    }

    /**
     * Set the value of tCity.
     *
     * @param string $tCity
     * @return \Entity\Campus
     */
    public function setTCity($tCity)
    {
        $this->tCity = $tCity;

        return $this;
    }

    /**
     * Get the value of tCity.
     *
     * @return string
     */
    public function getTCity()
    {
        return $this->tCity;
    }

    /**
     * Set the value of tState.
     *
     * @param string $tState
     * @return \Entity\Campus
     */
    public function setTState($tState)
    {
        $this->tState = $tState;

        return $this;
    }

    /**
     * Get the value of tState.
     *
     * @return string
     */
    public function getTState()
    {
        return $this->tState;
    }

    /**
     * Set the value of nCountry.
     *
     * @param integer $nCountry
     * @return \Entity\Campus
     */
    public function setNCountry($nCountry)
    {
        $this->nCountry = $nCountry;

        return $this;
    }

    /**
     * Get the value of nCountry.
     *
     * @return integer
     */
    public function getNCountry()
    {
        return $this->nCountry;
    }

    /**
     * Set the value of tZipCode.
     *
     * @param string $tZipCode
     * @return \Entity\Campus
     */
    public function setTZipCode($tZipCode)
    {
        $this->tZipCode = $tZipCode;

        return $this;
    }

    /**
     * Get the value of tZipCode.
     *
     * @return string
     */
    public function getTZipCode()
    {
        return $this->tZipCode;
    }

    /**
     * Set the value of nLatitude.
     *
     * @param float $nLatitude
     * @return \Entity\Campus
     */
    public function setNLatitude($nLatitude)
    {
        $this->nLatitude = $nLatitude;

        return $this;
    }

    /**
     * Get the value of nLatitude.
     *
     * @return float
     */
    public function getNLatitude()
    {
        return $this->nLatitude;
    }

    /**
     * Set the value of nLongitude.
     *
     * @param float $nLongitude
     * @return \Entity\Campus
     */
    public function setNLongitude($nLongitude)
    {
        $this->nLongitude = $nLongitude;

        return $this;
    }

    /**
     * Get the value of nLongitude.
     *
     * @return float
     */
    public function getNLongitude()
    {
        return $this->nLongitude;
    }

    /**
     * Set the value of dCreatedAt.
     *
     * @param \DateTime $dCreatedAt
     * @return \Entity\Campus
     */
    public function setDCreatedAt($dCreatedAt)
    {
        $this->dCreatedAt = $dCreatedAt;

        return $this;
    }

    /**
     * Get the value of dCreatedAt.
     *
     * @return \DateTime
     */
    public function getDCreatedAt()
    {
        return $this->dCreatedAt;
    }

    /**
     * Set the value of dUpdatedAt.
     *
     * @param \DateTime $dUpdatedAt
     * @return \Entity\Campus
     */
    public function setDUpdatedAt($dUpdatedAt)
    {
        $this->dUpdatedAt = $dUpdatedAt;

        return $this;
    }

    /**
     * Get the value of dUpdatedAt.
     *
     * @return \DateTime
     */
    public function getDUpdatedAt()
    {
        return $this->dUpdatedAt;
    }

    /**
     * Set the value of university_id.
     *
     * @param integer $university_id
     * @return \Entity\Campus
     */
    public function setUniversityId($university_id)
    {
        $this->university_id = $university_id;

        return $this;
    }

    /**
     * Get the value of university_id.
     *
     * @return integer
     */
    public function getUniversityId()
    {
        return $this->university_id;
    }

    /**
     * Add CampusHasProperty entity to collection (one to many).
     *
     * @param \Entity\CampusHasProperty $campusHasProperty
     * @return \Entity\Campus
     */
    public function addCampusHasProperty(CampusHasProperty $campusHasProperty)
    {
        $this->campusHasProperties[] = $campusHasProperty;

        return $this;
    }

    /**
     * Remove CampusHasProperty entity from collection (one to many).
     *
     * @param \Entity\CampusHasProperty $campusHasProperty
     * @return \Entity\Campus
     */
    public function removeCampusHasProperty(CampusHasProperty $campusHasProperty)
    {
        $this->campusHasProperties->removeElement($campusHasProperty);

        return $this;
    }

    /**
     * Get CampusHasProperty entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCampusHasProperties()
    {
        return $this->campusHasProperties;
    }

    /**
     * Set University entity (many to one).
     *
     * @param \Entity\University $university
     * @return \Entity\Campus
     */
    public function setUniversity(University $university = null)
    {
        $this->university = $university;

        return $this;
    }

    /**
     * Get University entity (many to one).
     *
     * @return \Entity\University
     */
    public function getUniversity()
    {
        return $this->university;
    }

    public function __sleep()
    {
        return array('id', 'tTitle', 'tDescription', 'bIsMain', 'tCampusCode', 'dEstablishmentYear', 'tAddressTitle', 'tStreet1', 'tStreet2', 'tCity', 'tState', 'nCountry', 'tZipCode', 'nLatitude', 'nLongitude', 'dCreatedAt', 'dUpdatedAt', 'university_id');
    }
}