<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-12 15:16:43.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */
namespace Tracestay\Bundle\TracestayBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity\CampusHasProperty
 *
 * @ORM\Entity(repositoryClass="CampusHasPropertyRepository")
 * @ORM\Table(name="campusHasProperty", indexes={@ORM\Index(name="fk_campus_has_property_property1_idx", columns={"propertyId"}), @ORM\Index(name="fk_campus_has_property_campus1_idx", columns={"campusId"})})
 */
class CampusHasProperty
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $campusId;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $propertyId;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Campus", inversedBy="campusHasProperties")
     * @ORM\JoinColumn(name="campusId", referencedColumnName="id")
     */
    protected $campus;

    /**
     * @ORM\ManyToOne(targetEntity="Property", inversedBy="campusHasProperties")
     * @ORM\JoinColumn(name="propertyId", referencedColumnName="id")
     */
    protected $property;

    public function __construct()
    {
    }

    /**
     * Set the value of campusId.
     *
     * @param integer $campusId
     * @return \Entity\CampusHasProperty
     */
    public function setCampusId($campusId)
    {
        $this->campusId = $campusId;

        return $this;
    }

    /**
     * Get the value of campusId.
     *
     * @return integer
     */
    public function getCampusId()
    {
        return $this->campusId;
    }

    /**
     * Set the value of propertyId.
     *
     * @param integer $propertyId
     * @return \Entity\CampusHasProperty
     */
    public function setPropertyId($propertyId)
    {
        $this->propertyId = $propertyId;

        return $this;
    }

    /**
     * Get the value of propertyId.
     *
     * @return integer
     */
    public function getPropertyId()
    {
        return $this->propertyId;
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\CampusHasProperty
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set Campus entity (many to one).
     *
     * @param \Entity\Campus $campus
     * @return \Entity\CampusHasProperty
     */
    public function setCampus(Campus $campus = null)
    {
        $this->campus = $campus;

        return $this;
    }

    /**
     * Get Campus entity (many to one).
     *
     * @return \Entity\Campus
     */
    public function getCampus()
    {
        return $this->campus;
    }

    /**
     * Set Property entity (many to one).
     *
     * @param \Entity\Property $property
     * @return \Entity\CampusHasProperty
     */
    public function setProperty(Property $property = null)
    {
        $this->property = $property;

        return $this;
    }

    /**
     * Get Property entity (many to one).
     *
     * @return \Entity\Property
     */
    public function getProperty()
    {
        return $this->property;
    }

    public function __sleep()
    {
        return array('campusId', 'propertyId', 'id');
    }
}