<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-12 13:31:19.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity\ListingSetting
 *
 * @ORM\Entity(repositoryClass="ListingSettingRepository")
 * @ORM\Table(name="listing_setting", indexes={@ORM\Index(name="fk_listing_setting_address_visibility1_idx", columns={"addressVisibilityId"}), @ORM\Index(name="fk_listing_setting_university1_idx", columns={"university_id"})})
 */
class ListingSetting
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $addressVisibilityId;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $nAdvertisePeriod;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $nBondPeriod;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $bPhotoRequired;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $bEnableBadges;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $bEnableStarRatings;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $nStarRating;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $dCreatedAt;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $dUpdatedAt;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $university_id;

    /**
     * @ORM\ManyToOne(targetEntity="AddressVisibility", inversedBy="listingSettings")
     * @ORM\JoinColumn(name="addressVisibilityId", referencedColumnName="id")
     */
    protected $addressVisibility;

    /**
     * @ORM\ManyToOne(targetEntity="University", inversedBy="listingSettings")
     * @ORM\JoinColumn(name="university_id", referencedColumnName="id")
     */
    protected $university;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\ListingSetting
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of addressVisibilityId.
     *
     * @param integer $addressVisibilityId
     * @return \Entity\ListingSetting
     */
    public function setAddressVisibilityId($addressVisibilityId)
    {
        $this->addressVisibilityId = $addressVisibilityId;

        return $this;
    }

    /**
     * Get the value of addressVisibilityId.
     *
     * @return integer
     */
    public function getAddressVisibilityId()
    {
        return $this->addressVisibilityId;
    }

    /**
     * Set the value of nAdvertisePeriod.
     *
     * @param integer $nAdvertisePeriod
     * @return \Entity\ListingSetting
     */
    public function setNAdvertisePeriod($nAdvertisePeriod)
    {
        $this->nAdvertisePeriod = $nAdvertisePeriod;

        return $this;
    }

    /**
     * Get the value of nAdvertisePeriod.
     *
     * @return integer
     */
    public function getNAdvertisePeriod()
    {
        return $this->nAdvertisePeriod;
    }

    /**
     * Set the value of nBondPeriod.
     *
     * @param integer $nBondPeriod
     * @return \Entity\ListingSetting
     */
    public function setNBondPeriod($nBondPeriod)
    {
        $this->nBondPeriod = $nBondPeriod;

        return $this;
    }

    /**
     * Get the value of nBondPeriod.
     *
     * @return integer
     */
    public function getNBondPeriod()
    {
        return $this->nBondPeriod;
    }

    /**
     * Set the value of bPhotoRequired.
     *
     * @param boolean $bPhotoRequired
     * @return \Entity\ListingSetting
     */
    public function setBPhotoRequired($bPhotoRequired)
    {
        $this->bPhotoRequired = $bPhotoRequired;

        return $this;
    }

    /**
     * Get the value of bPhotoRequired.
     *
     * @return boolean
     */
    public function getBPhotoRequired()
    {
        return $this->bPhotoRequired;
    }

    /**
     * Set the value of bEnableBadges.
     *
     * @param boolean $bEnableBadges
     * @return \Entity\ListingSetting
     */
    public function setBEnableBadges($bEnableBadges)
    {
        $this->bEnableBadges = $bEnableBadges;

        return $this;
    }

    /**
     * Get the value of bEnableBadges.
     *
     * @return boolean
     */
    public function getBEnableBadges()
    {
        return $this->bEnableBadges;
    }

    /**
     * Set the value of bEnableStarRatings.
     *
     * @param boolean $bEnableStarRatings
     * @return \Entity\ListingSetting
     */
    public function setBEnableStarRatings($bEnableStarRatings)
    {
        $this->bEnableStarRatings = $bEnableStarRatings;

        return $this;
    }

    /**
     * Get the value of bEnableStarRatings.
     *
     * @return boolean
     */
    public function getBEnableStarRatings()
    {
        return $this->bEnableStarRatings;
    }

    /**
     * Set the value of nStarRating.
     *
     * @param integer $nStarRating
     * @return \Entity\ListingSetting
     */
    public function setNStarRating($nStarRating)
    {
        $this->nStarRating = $nStarRating;

        return $this;
    }

    /**
     * Get the value of nStarRating.
     *
     * @return integer
     */
    public function getNStarRating()
    {
        return $this->nStarRating;
    }

    /**
     * Set the value of dCreatedAt.
     *
     * @param \DateTime $dCreatedAt
     * @return \Entity\ListingSetting
     */
    public function setDCreatedAt($dCreatedAt)
    {
        $this->dCreatedAt = $dCreatedAt;

        return $this;
    }

    /**
     * Get the value of dCreatedAt.
     *
     * @return \DateTime
     */
    public function getDCreatedAt()
    {
        return $this->dCreatedAt;
    }

    /**
     * Set the value of dUpdatedAt.
     *
     * @param integer $dUpdatedAt
     * @return \Entity\ListingSetting
     */
    public function setDUpdatedAt($dUpdatedAt)
    {
        $this->dUpdatedAt = $dUpdatedAt;

        return $this;
    }

    /**
     * Get the value of dUpdatedAt.
     *
     * @return integer
     */
    public function getDUpdatedAt()
    {
        return $this->dUpdatedAt;
    }

    /**
     * Set the value of university_id.
     *
     * @param integer $university_id
     * @return \Entity\ListingSetting
     */
    public function setUniversityId($university_id)
    {
        $this->university_id = $university_id;

        return $this;
    }

    /**
     * Get the value of university_id.
     *
     * @return integer
     */
    public function getUniversityId()
    {
        return $this->university_id;
    }

    /**
     * Set AddressVisibility entity (many to one).
     *
     * @param \Entity\AddressVisibility $addressVisibility
     * @return \Entity\ListingSetting
     */
    public function setAddressVisibility(AddressVisibility $addressVisibility = null)
    {
        $this->addressVisibility = $addressVisibility;

        return $this;
    }

    /**
     * Get AddressVisibility entity (many to one).
     *
     * @return \Entity\AddressVisibility
     */
    public function getAddressVisibility()
    {
        return $this->addressVisibility;
    }

    /**
     * Set University entity (many to one).
     *
     * @param \Entity\University $university
     * @return \Entity\ListingSetting
     */
    public function setUniversity(University $university = null)
    {
        $this->university = $university;

        return $this;
    }

    /**
     * Get University entity (many to one).
     *
     * @return \Entity\University
     */
    public function getUniversity()
    {
        return $this->university;
    }

    public function __sleep()
    {
        return array('id', 'addressVisibilityId', 'nAdvertisePeriod', 'nBondPeriod', 'bPhotoRequired', 'bEnableBadges', 'bEnableStarRatings', 'nStarRating', 'dCreatedAt', 'dUpdatedAt', 'university_id');
    }
}