<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-12 13:31:19.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity\Payment
 *
 * @ORM\Entity(repositoryClass="PaymentRepository")
 * @ORM\Table(name="payment", indexes={@ORM\Index(name="fk_payment_invoice1_idx", columns={"invoiceId"})})
 */
class Payment
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $invoiceId;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $nInvoiceAmount;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $nAmountPaid;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $dCreatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $dUpdatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="Invoice", inversedBy="payments")
     * @ORM\JoinColumn(name="invoiceId", referencedColumnName="id")
     */
    protected $invoice;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\Payment
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of invoiceId.
     *
     * @param integer $invoiceId
     * @return \Entity\Payment
     */
    public function setInvoiceId($invoiceId)
    {
        $this->invoiceId = $invoiceId;

        return $this;
    }

    /**
     * Get the value of invoiceId.
     *
     * @return integer
     */
    public function getInvoiceId()
    {
        return $this->invoiceId;
    }

    /**
     * Set the value of nInvoiceAmount.
     *
     * @param float $nInvoiceAmount
     * @return \Entity\Payment
     */
    public function setNInvoiceAmount($nInvoiceAmount)
    {
        $this->nInvoiceAmount = $nInvoiceAmount;

        return $this;
    }

    /**
     * Get the value of nInvoiceAmount.
     *
     * @return float
     */
    public function getNInvoiceAmount()
    {
        return $this->nInvoiceAmount;
    }

    /**
     * Set the value of nAmountPaid.
     *
     * @param float $nAmountPaid
     * @return \Entity\Payment
     */
    public function setNAmountPaid($nAmountPaid)
    {
        $this->nAmountPaid = $nAmountPaid;

        return $this;
    }

    /**
     * Get the value of nAmountPaid.
     *
     * @return float
     */
    public function getNAmountPaid()
    {
        return $this->nAmountPaid;
    }

    /**
     * Set the value of dCreatedAt.
     *
     * @param \DateTime $dCreatedAt
     * @return \Entity\Payment
     */
    public function setDCreatedAt($dCreatedAt)
    {
        $this->dCreatedAt = $dCreatedAt;

        return $this;
    }

    /**
     * Get the value of dCreatedAt.
     *
     * @return \DateTime
     */
    public function getDCreatedAt()
    {
        return $this->dCreatedAt;
    }

    /**
     * Set the value of dUpdatedAt.
     *
     * @param \DateTime $dUpdatedAt
     * @return \Entity\Payment
     */
    public function setDUpdatedAt($dUpdatedAt)
    {
        $this->dUpdatedAt = $dUpdatedAt;

        return $this;
    }

    /**
     * Get the value of dUpdatedAt.
     *
     * @return \DateTime
     */
    public function getDUpdatedAt()
    {
        return $this->dUpdatedAt;
    }

    /**
     * Set Invoice entity (many to one).
     *
     * @param \Entity\Invoice $invoice
     * @return \Entity\Payment
     */
    public function setInvoice(Invoice $invoice = null)
    {
        $this->invoice = $invoice;

        return $this;
    }

    /**
     * Get Invoice entity (many to one).
     *
     * @return \Entity\Invoice
     */
    public function getInvoice()
    {
        return $this->invoice;
    }

    public function __sleep()
    {
        return array('id', 'invoiceId', 'nInvoiceAmount', 'nAmountPaid', 'dCreatedAt', 'dUpdatedAt');
    }
}