<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-12 15:16:43.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */
namespace Tracestay\Bundle\TracestayBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity\Plan
 *
 * @ORM\Entity(repositoryClass="PlanRepository")
 * @ORM\Table(name="`plan`", indexes={@ORM\Index(name="fk_plan_currencyCode1_idx", columns={"currencyCodeId"}), @ORM\Index(name="fk_plan_university1_idx", columns={"university_id"})})
 */
class Plan
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $currencyCodeId;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $university_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $nListingName;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $nAdminAccounts;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $bEmailSupport;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $bPhoneSupport;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $bMailouts;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $bSslSetup;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $dCreatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $dUpdatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="CurrencyCode", inversedBy="plans")
     * @ORM\JoinColumn(name="currencyCodeId", referencedColumnName="id")
     */
    protected $currencyCode;

    /**
     * @ORM\OneToOne(targetEntity="University", inversedBy="plan")
     * @ORM\JoinColumn(name="university_id", referencedColumnName="id")
     */
    protected $university;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\Plan
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of currencyCodeId.
     *
     * @param integer $currencyCodeId
     * @return \Entity\Plan
     */
    public function setCurrencyCodeId($currencyCodeId)
    {
        $this->currencyCodeId = $currencyCodeId;

        return $this;
    }

    /**
     * Get the value of currencyCodeId.
     *
     * @return integer
     */
    public function getCurrencyCodeId()
    {
        return $this->currencyCodeId;
    }

    /**
     * Set the value of university_id.
     *
     * @param integer $university_id
     * @return \Entity\Plan
     */
    public function setUniversityId($university_id)
    {
        $this->university_id = $university_id;

        return $this;
    }

    /**
     * Get the value of university_id.
     *
     * @return integer
     */
    public function getUniversityId()
    {
        return $this->university_id;
    }

    /**
     * Set the value of nListingName.
     *
     * @param integer $nListingName
     * @return \Entity\Plan
     */
    public function setNListingName($nListingName)
    {
        $this->nListingName = $nListingName;

        return $this;
    }

    /**
     * Get the value of nListingName.
     *
     * @return integer
     */
    public function getNListingName()
    {
        return $this->nListingName;
    }

    /**
     * Set the value of nAdminAccounts.
     *
     * @param integer $nAdminAccounts
     * @return \Entity\Plan
     */
    public function setNAdminAccounts($nAdminAccounts)
    {
        $this->nAdminAccounts = $nAdminAccounts;

        return $this;
    }

    /**
     * Get the value of nAdminAccounts.
     *
     * @return integer
     */
    public function getNAdminAccounts()
    {
        return $this->nAdminAccounts;
    }

    /**
     * Set the value of bEmailSupport.
     *
     * @param boolean $bEmailSupport
     * @return \Entity\Plan
     */
    public function setBEmailSupport($bEmailSupport)
    {
        $this->bEmailSupport = $bEmailSupport;

        return $this;
    }

    /**
     * Get the value of bEmailSupport.
     *
     * @return boolean
     */
    public function getBEmailSupport()
    {
        return $this->bEmailSupport;
    }

    /**
     * Set the value of bPhoneSupport.
     *
     * @param boolean $bPhoneSupport
     * @return \Entity\Plan
     */
    public function setBPhoneSupport($bPhoneSupport)
    {
        $this->bPhoneSupport = $bPhoneSupport;

        return $this;
    }

    /**
     * Get the value of bPhoneSupport.
     *
     * @return boolean
     */
    public function getBPhoneSupport()
    {
        return $this->bPhoneSupport;
    }

    /**
     * Set the value of bMailouts.
     *
     * @param boolean $bMailouts
     * @return \Entity\Plan
     */
    public function setBMailouts($bMailouts)
    {
        $this->bMailouts = $bMailouts;

        return $this;
    }

    /**
     * Get the value of bMailouts.
     *
     * @return boolean
     */
    public function getBMailouts()
    {
        return $this->bMailouts;
    }

    /**
     * Set the value of bSslSetup.
     *
     * @param boolean $bSslSetup
     * @return \Entity\Plan
     */
    public function setBSslSetup($bSslSetup)
    {
        $this->bSslSetup = $bSslSetup;

        return $this;
    }

    /**
     * Get the value of bSslSetup.
     *
     * @return boolean
     */
    public function getBSslSetup()
    {
        return $this->bSslSetup;
    }

    /**
     * Set the value of dCreatedAt.
     *
     * @param \DateTime $dCreatedAt
     * @return \Entity\Plan
     */
    public function setDCreatedAt($dCreatedAt)
    {
        $this->dCreatedAt = $dCreatedAt;

        return $this;
    }

    /**
     * Get the value of dCreatedAt.
     *
     * @return \DateTime
     */
    public function getDCreatedAt()
    {
        return $this->dCreatedAt;
    }

    /**
     * Set the value of dUpdatedAt.
     *
     * @param \DateTime $dUpdatedAt
     * @return \Entity\Plan
     */
    public function setDUpdatedAt($dUpdatedAt)
    {
        $this->dUpdatedAt = $dUpdatedAt;

        return $this;
    }

    /**
     * Get the value of dUpdatedAt.
     *
     * @return \DateTime
     */
    public function getDUpdatedAt()
    {
        return $this->dUpdatedAt;
    }

    /**
     * Set CurrencyCode entity (many to one).
     *
     * @param \Entity\CurrencyCode $currencyCode
     * @return \Entity\Plan
     */
    public function setCurrencyCode(CurrencyCode $currencyCode = null)
    {
        $this->currencyCode = $currencyCode;

        return $this;
    }

    /**
     * Get CurrencyCode entity (many to one).
     *
     * @return \Entity\CurrencyCode
     */
    public function getCurrencyCode()
    {
        return $this->currencyCode;
    }

    /**
     * Set University entity (one to one).
     *
     * @param \Entity\University $university
     * @return \Entity\Plan
     */
    public function setUniversity(University $university)
    {
        $this->university = $university;

        return $this;
    }

    /**
     * Get University entity (one to one).
     *
     * @return \Entity\University
     */
    public function getUniversity()
    {
        return $this->university;
    }

    public function __sleep()
    {
        return array('id', 'currencyCodeId', 'university_id', 'nListingName', 'nAdminAccounts', 'bEmailSupport', 'bPhoneSupport', 'bMailouts', 'bSslSetup', 'dCreatedAt', 'dUpdatedAt');
    }
}