<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-12 15:16:43.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Entity\TimeZone
 *
 * @ORM\Entity(repositoryClass="TimeZoneRepository")
 * @ORM\Table(name="timeZone")
 */
class TimeZone
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $nTimeZone;

    /**
     * @ORM\OneToMany(targetEntity="WebsiteSetting", mappedBy="timeZone")
     * @ORM\JoinColumn(name="id", referencedColumnName="timeZoneId")
     */
    protected $websiteSettings;

    public function __construct()
    {
        $this->websiteSettings = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\TimeZone
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of nTimeZone.
     *
     * @param integer $nTimeZone
     * @return \Entity\TimeZone
     */
    public function setNTimeZone($nTimeZone)
    {
        $this->nTimeZone = $nTimeZone;

        return $this;
    }

    /**
     * Get the value of nTimeZone.
     *
     * @return integer
     */
    public function getNTimeZone()
    {
        return $this->nTimeZone;
    }

    /**
     * Add WebsiteSetting entity to collection (one to many).
     *
     * @param \Entity\WebsiteSetting $websiteSetting
     * @return \Entity\TimeZone
     */
    public function addWebsiteSetting(WebsiteSetting $websiteSetting)
    {
        $this->websiteSettings[] = $websiteSetting;

        return $this;
    }

    /**
     * Remove WebsiteSetting entity from collection (one to many).
     *
     * @param \Entity\WebsiteSetting $websiteSetting
     * @return \Entity\TimeZone
     */
    public function removeWebsiteSetting(WebsiteSetting $websiteSetting)
    {
        $this->websiteSettings->removeElement($websiteSetting);

        return $this;
    }

    /**
     * Get WebsiteSetting entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getWebsiteSettings()
    {
        return $this->websiteSettings;
    }

    public function __sleep()
    {
        return array('id', 'nTimeZone');
    }
}